/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UvButton {
        "callback"?: Function;
        "disabled": boolean;
    }
}
declare global {
    interface HTMLUvButtonElement extends Components.UvButton, HTMLStencilElement {
    }
    var HTMLUvButtonElement: {
        prototype: HTMLUvButtonElement;
        new (): HTMLUvButtonElement;
    };
    interface HTMLElementTagNameMap {
        "uv-button": HTMLUvButtonElement;
    }
}
declare namespace LocalJSX {
    interface UvButton {
        "callback"?: Function;
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "uv-button": UvButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uv-button": LocalJSX.UvButton & JSXBase.HTMLAttributes<HTMLUvButtonElement>;
        }
    }
}
